# Generated by Django 2.2.2 on 2019-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(default='', max_length=120),
        ),
    ]
